In [98]:
import pandas as pd
cpi = pd.read_csv('CPI.csv')

In [100]:
cpi

,COUNTRY,COUNTRY_CODE,REGION,2022-M01,2022-M02,2022-M03,2022-M04,2022-M05,2022-M06,2022-M07,...,2024-M07,2024-M08,2024-M09,2024-M10,2024-M11,2024-M12,2025-M01,2025-M02,2025-M03,2025-M04
0,Oman,OM,Middle East - GCC,104.000000,103.500000,103.700000,104.100000,104.000000,104.200000,104.600000,...,106.300000,106.100000,106.100000,106.400000,106.300000,NaN,NaN,NaN,NaN,NaN
1,Cambodia,KH,RO APAC,193.100000,195.400000,198.560000,198.802000,200.388000,201.991000,199.281000,...,204.323000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Indonesia,ID,RO APAC,144.725400,144.698600,145.647800,147.024700,147.612900,148.508600,149.457800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Macao Special Administrative Region, People's ...",MO,Greater China,103.312974,103.404446,103.388650,103.555040,103.641603,103.859886,103.947452,...,105.064448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Nepal,NP,RO APAC,144.840000,144.850000,146.150000,147.340000,149.440000,151.040000,151.670000,...,168.770000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,"China, People's Republic of",CN,Greater China,101.900000,102.500000,102.500000,102.900000,102.700000,102.700000,103.200000,...,103.400000,103.800000,103.800000,103.600000,103.000000,103.000000,103.600000,103.400000,103.200000,103.123000
76,Czech Republic,CZ,EU,124.600000,126.200000,128.300000,130.600000,132.900000,135.000000,136.800000,...,152.000000,152.400000,151.800000,152.300000,152.400000,152.000000,154.000000,154.300000,154.400000,154.200000
77,"Latvia, Republic of",LV,EU,116.810100,118.712800,122.650200,125.387900,130.344200,133.500600,136.423800,...,146.178900,145.409900,145.794600,146.104400,146.393600,146.699200,147.577200,148.688900,149.996300,151.592000
78,United States,US,North America,128.934147,130.111829,131.849002,132.585053,134.046607,135.887882,135.871831,...,144.247680,144.365081,144.596674,144.763145,144.684725,144.736088,145.683553,146.330636,146.659451,147.116216
79,"Netherlands, The",NL,EU,114.530000,115.270000,119.460000,119.810000,119.050000,119.050000,121.570000,...,131.820000,132.240000,131.610000,132.260000,131.480000,131.630000,131.350000,132.800000,133.330000,134.720000

In [102]:
# 转换为长格式
cpi_long = pd.melt(cpi,
                  id_vars=['COUNTRY', 'COUNTRY_CODE', 'REGION'],  # 保持不变的列
                  var_name='MONTH',       # 新的列名（原来的列名如2022-M01）
                  value_name='VALUE')     # 新的数值列

cpi_long = cpi_long.sort_values(['COUNTRY', 'MONTH'])  # 确保顺序
cpi_long

,COUNTRY,COUNTRY_CODE,REGION,MONTH,VALUE
11,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M01,139.421705
91,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M02,140.309161
171,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M03,140.832836
251,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M04,143.059494
331,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M05,144.404200
...,...,...,...,...,...
2857,West Bank and Gaza,PS,RO APAC,2024-M12,231.650000
2937,West Bank and Gaza,PS,RO APAC,2025-M01,156.230000
3017,West Bank and Gaza,PS,RO APAC,2025-M02,134.230000
3097,West Bank and Gaza,PS,RO APAC,2025-M03,153.080000
3177,West Bank and Gaza,PS,RO APAC,2025-M04,NaN

In [104]:
cpi_long['VALUE'] = cpi_long.groupby('COUNTRY')['VALUE'].ffill().bfill()

# 保存为新的文件
cpi_long.to_csv('CPI_long_format.csv', index=False)

cpi_long

,COUNTRY,COUNTRY_CODE,REGION,MONTH,VALUE
11,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M01,139.421705
91,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M02,140.309161
171,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M03,140.832836
251,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M04,143.059494
331,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M05,144.404200
...,...,...,...,...,...
2857,West Bank and Gaza,PS,RO APAC,2024-M12,231.650000
2937,West Bank and Gaza,PS,RO APAC,2025-M01,156.230000
3017,West Bank and Gaza,PS,RO APAC,2025-M02,134.230000
3097,West Bank and Gaza,PS,RO APAC,2025-M03,153.080000
3177,West Bank and Gaza,PS,RO APAC,2025-M04,153.080000

In [106]:
df_cpi= pd.read_csv('CPI_long_format.csv')

In [108]:
df_cpi['YEAR'] = df_cpi['MONTH'].str.extract(r'(\d{4})').astype(int)
df_cpi

,COUNTRY,COUNTRY_CODE,REGION,MONTH,VALUE,YEAR
0,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M01,139.421705,2022
1,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M02,140.309161,2022
2,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M03,140.832836,2022
3,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M04,143.059494,2022
4,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M05,144.404200,2022
...,...,...,...,...,...,...
3195,West Bank and Gaza,PS,RO APAC,2024-M12,231.650000,2024
3196,West Bank and Gaza,PS,RO APAC,2025-M01,156.230000,2025
3197,West Bank and Gaza,PS,RO APAC,2025-M02,134.230000,2025
3198,West Bank and Gaza,PS,RO APAC,2025-M03,153.080000,2025
3199,West Bank and Gaza,PS,RO APAC,2025-M04,153.080000,2025

In [110]:
df_gdp = pd.read_csv('GDP.csv')
df_gdp = pd.melt(df_gdp,
                      id_vars=['COUNTRY', 'COUNTRY_CODE', 'REGION'],
                      var_name='YEAR',
                      value_name='GDP')
df_gdp['YEAR'] = df_gdp['YEAR'].astype(int)

df_gdp = df_gdp.sort_values(['COUNTRY', 'YEAR'])

df_gdp['GDP'] = df_gdp.groupby('COUNTRY')['GDP'].ffill().bfill()
df_gdp

                              COUNTRY COUNTRY_CODE   REGION  YEAR      GDP
58   Afghanistan, Islamic Republic of           AF  RO APAC  2022   14.501
138  Afghanistan, Islamic Republic of           AF  RO APAC  2023   17.248
218  Afghanistan, Islamic Republic of           AF  RO APAC  2024   17.248
298  Afghanistan, Islamic Republic of           AF  RO APAC  2025   17.248
3                Armenia, Republic of           AM  RO APAC  2022   19.514
..                                ...          ...      ...   ...      ...
296                           Vietnam           VN  RO APAC  2025  490.970
21                 West Bank and Gaza           PS  RO APAC  2022   19.166
101                West Bank and Gaza           PS  RO APAC  2023   17.848
181                West Bank and Gaza           PS  RO APAC  2024   17.848
261                West Bank and Gaza           PS  RO APAC  2025   17.848

[320 rows x 5 columns]

In [112]:
df_merged_cpi = pd.merge(df_cpi, df_gdp, on=['COUNTRY','COUNTRY_CODE', 'REGION', 'YEAR'], how='inner')
df_merged_cpi

,COUNTRY,COUNTRY_CODE,REGION,MONTH,VALUE,YEAR,GDP
0,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M01,139.421705,2022,14.501
1,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M02,140.309161,2022,14.501
2,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M03,140.832836,2022,14.501
3,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M04,143.059494,2022,14.501
4,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M05,144.404200,2022,14.501
...,...,...,...,...,...,...,...
3195,West Bank and Gaza,PS,RO APAC,2024-M12,231.650000,2024,17.848
3196,West Bank and Gaza,PS,RO APAC,2025-M01,156.230000,2025,17.848
3197,West Bank and Gaza,PS,RO APAC,2025-M02,134.230000,2025,17.848
3198,West Bank and Gaza,PS,RO APAC,2025-M03,153.080000,2025,17.848
3199,West Bank and Gaza,PS,RO APAC,2025-M04,153.080000,2025,17.848

In [114]:
df_merged_cpi['GDP_WEIGHTED_CPI'] = df_merged_cpi['VALUE'] * df_merged_cpi['GDP']
df_merged_cpi

,COUNTRY,COUNTRY_CODE,REGION,MONTH,VALUE,YEAR,GDP,GDP_WEIGHTED_CPI
0,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M01,139.421705,2022,14.501,2021.754147
1,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M02,140.309161,2022,14.501,2034.623145
2,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M03,140.832836,2022,14.501,2042.216958
3,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M04,143.059494,2022,14.501,2074.505721
4,"Afghanistan, Islamic Republic of",AF,RO APAC,2022-M05,144.404200,2022,14.501,2094.005304
...,...,...,...,...,...,...,...,...
3195,West Bank and Gaza,PS,RO APAC,2024-M12,231.650000,2024,17.848,4134.489200
3196,West Bank and Gaza,PS,RO APAC,2025-M01,156.230000,2025,17.848,2788.393040
3197,West Bank and Gaza,PS,RO APAC,2025-M02,134.230000,2025,17.848,2395.737040
3198,West Bank and Gaza,PS,RO APAC,2025-M03,153.080000,2025,17.848,2732.171840
3199,West Bank and Gaza,PS,RO APAC,2025-M04,153.080000,2025,17.848,2732.171840

In [116]:
df_cpi_result = (
    df_merged_cpi
    .groupby(['REGION', 'MONTH'])
    .apply(lambda g: g['GDP_WEIGHTED_CPI'].sum() / g['GDP'].sum())
    .reset_index(name='REGION_CPI_WEIGHTED')
)
df_cpi_result

/var/folders/j9/2kb4w8sd2qn_ry70r38f81th0000gn/T/ipykernel_59212/2093896961.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g['GDP_WEIGHTED_CPI'].sum() / g['GDP'].sum())

    REGION     MONTH  REGION_CPI_WEIGHTED
0       EU  2022-M01           160.346850
1       EU  2022-M02           161.870266
2       EU  2022-M03           165.086737
3       EU  2022-M04           167.005486
4       EU  2022-M05           168.626610
..     ...       ...                  ...
275     UK  2024-M12           135.100000
276     UK  2025-M01           135.100000
277     UK  2025-M02           135.600000
278     UK  2025-M03           136.100000
279     UK  2025-M04           136.100000

[280 rows x 3 columns]

In [118]:
df_cpi_result['MONTH'] = df_cpi_result['MONTH'].str.replace('-M', '/')
df_cpi_result.to_csv('region_weighted_cpi.csv', index=False)

In [120]:
df_cpi_result

    REGION    MONTH  REGION_CPI_WEIGHTED
0       EU  2022/01           160.346850
1       EU  2022/02           161.870266
2       EU  2022/03           165.086737
3       EU  2022/04           167.005486
4       EU  2022/05           168.626610
..     ...      ...                  ...
275     UK  2024/12           135.100000
276     UK  2025/01           135.100000
277     UK  2025/02           135.600000
278     UK  2025/03           136.100000
279     UK  2025/04           136.100000

[280 rows x 3 columns]

In [123]:
df_flight = pd.read_csv('merged_week_country.csv')                
df_cpi = pd.read_csv('region_weighted_cpi.csv')  
df_cpi = df_cpi.rename(columns={'REGION': 'COUNTRY'})

In [129]:
df_flight

,Unnamed: 0,DATE,COUNTRY,TRANSACTIONS,ARRIVALS,LHR_arrivals,non_LHR_arrivals,premium_economy_and_above_arrivals,business_and_above_arrivals,first_arrivals,transactions_non_target,transactions_target,transactions_bronze_and_above,transactions_gold_and_above,transactions_black_and_above,transactions_platinum_and_above,transactions_elite_and_above,MONTH
0,0,2022-01-31,EU,465,22568,4396,18172,632,384,14,73.0,392.0,302,224,157,44,6,2022/01
1,1,2022-01-31,Greater China,764,84,84,0,13,9,0,98.0,666.0,603,510,352,154,45,2022/01
2,2,2022-01-31,Middle East - GCC,901,1463,1330,133,482,263,29,120.0,781.0,704,564,429,140,47,2022/01
3,3,2022-01-31,North America,430,4189,3903,286,929,602,54,133.0,297.0,253,175,125,35,19,2022/01
4,4,2022-01-31,RO APAC,323,2945,2375,570,686,484,35,57.0,266.0,230,186,118,59,27,2022/01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,845,2025-04-28,EU,2503,163175,55909,107266,3886,2571,-372,1154.0,1349.0,1563,1309,1012,336,16,2025/04
846,846,2025-04-28,Greater China,3441,6461,4968,1493,795,421,-234,1075.0,2366.0,3056,2735,2279,1081,102,2025/04
847,847,2025-04-28,Middle East - GCC,4859,11296,9414,1882,2615,2152,174,1228.0,3631.0,4173,3540,2781,1085,173,2025/04
848,848,2025-04-28,North America,1798,67847,64922,2925,20003,10999,-1569,952.0,846.0,1023,770,526,108,20,2025/04
849,849,2025-04-28,RO APAC,1634,33500,22644,10856,6557,4567,-677,589.0,1045.0,1197,1052,861,342,52,2025/04

In [125]:
df_flight['MONTH'] = pd.to_datetime(df_flight['DATE'], dayfirst=True).dt.strftime('%Y/%m')
df_merged = pd.merge(df_flight, df_cpi, on=['COUNTRY', 'MONTH'], how='left')
df_merged

/var/folders/j9/2kb4w8sd2qn_ry70r38f81th0000gn/T/ipykernel_59212/71959357.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df_flight['MONTH'] = pd.to_datetime(df_flight['DATE'], dayfirst=True).dt.strftime('%Y/%m')

,Unnamed: 0,DATE,COUNTRY,TRANSACTIONS,ARRIVALS,LHR_arrivals,non_LHR_arrivals,premium_economy_and_above_arrivals,business_and_above_arrivals,first_arrivals,transactions_non_target,transactions_target,transactions_bronze_and_above,transactions_gold_and_above,transactions_black_and_above,transactions_platinum_and_above,transactions_elite_and_above,MONTH,REGION_CPI_WEIGHTED
0,0,2022-01-31,EU,465,22568,4396,18172,632,384,14,73.0,392.0,302,224,157,44,6,2022/01,160.346850
1,1,2022-01-31,Greater China,764,84,84,0,13,9,0,98.0,666.0,603,510,352,154,45,2022/01,101.909566
2,2,2022-01-31,Middle East - GCC,901,1463,1330,133,482,263,29,120.0,781.0,704,564,429,140,47,2022/01,105.228390
3,3,2022-01-31,North America,430,4189,3903,286,929,602,54,133.0,297.0,253,175,125,35,19,2022/01,129.602179
4,4,2022-01-31,RO APAC,323,2945,2375,570,686,484,35,57.0,266.0,230,186,118,59,27,2022/01,157.517541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,845,2025-04-28,EU,2503,163175,55909,107266,3886,2571,-372,1154.0,1349.0,1563,1309,1012,336,16,2025/04,196.263202
846,846,2025-04-28,Greater China,3441,6461,4968,1493,795,421,-234,1075.0,2366.0,3056,2735,2279,1081,102,2025/04,103.246082
847,847,2025-04-28,Middle East - GCC,4859,11296,9414,1882,2615,2152,174,1228.0,3631.0,4173,3540,2781,1085,173,2025/04,112.476865
848,848,2025-04-28,North America,1798,67847,64922,2925,20003,10999,-1569,952.0,846.0,1023,770,526,108,20,2025/04,147.762774
849,849,2025-04-28,RO APAC,1634,33500,22644,10856,6557,4567,-677,589.0,1045.0,1197,1052,861,342,52,2025/04,380.775804

In [127]:
df_merged.to_csv('CPI_merged_data.csv', index=False)